# Device builds and TestFlight are disabled in this sample repository.
default_platform(:ios)

platform :ios do
  lane :build do
    UI.user_error!('This sample is not configured to build or run on a device.')
  end

  lane :submit do
    UI.user_error!('This sample is not configured to submit to TestFlight.')
  end

  lane :beta do
    UI.user_error!('This sample is not configured to build or run on a device.')
  end
end
