#!/bin/bash
# Keep Homebrew CocoaPods free of user Ruby GEM_PATH (Gem::MissingSpecError).
unset GEM_PATH GEM_HOME RUBYOPT RUBYLIB
unset RUBY_ROOT RUBY_VERSION RUBY_ENGINE GEM_ROOT
export LANG="${LANG:-en_US.UTF-8}"
export LC_ALL="${LC_ALL:-en_US.UTF-8}"
exec /opt/homebrew/bin/pod "$@"
